# Generated by Django 5.0.1 on 2024-01-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSpeedLimitedConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(db_comment='user type 1: anonymous user,2:login user')),
                ('limited_qps', models.IntegerField(db_comment='limited qps. 1qps for anonymous user,10 qps  for  login user ')),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadNumberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.IntegerField()),
                ('file_upload_time', models.DateTimeField(verbose_name='file upload date time')),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_serial_no', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=64)),
                ('last_login_date_time', models.DateTimeField()),
                ('allowed_qps', models.IntegerField(default=10)),
                ('user_login_status', models.IntegerField(db_comment="1: login 2: don't login", default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
