# Generated by Django 5.0.1 on 2024-01-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadnumberrecord',
            name='login_user_id',
            field=models.BigIntegerField(default=-1, verbose_name='login user id'),
            preserve_default=False,
        ),
    ]
