# Generated by Django 5.0.1 on 2024-01-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_fileuploadnumberrecord_login_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filespeedlimitedconfiguration',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fileuploadnumberrecord',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
